name: crypto_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# Script
# Launch icon: flutter pub run flutter_launcher_icons
# flutter pub run build_runner build --delete-conflicting-outputs
# flutter pub run build_runner clean
# flutter pub run easy_localization:generate --source-dir 'assets/translations' --output-dir 'lib/generated' --output-file 'translations.g.dart' --format keys
# flutter build apk --flavor development --release -t lib/main_development.dart --build-name 1.0.1 --build-number 6 --no-tree-shake-icons
# flutter build apk --flavor production --release -t lib/main_production.dart --build-name 1.0.1 --build-number 6 --no-tree-shake-icons
# flutter build appbundle --flavor development --release -t lib/main_development.dart --build-name 1.0.1 --build-number 6
# flutter build appbundle --flavor production --release -t lib/main_production.dart --build-name 1.0.1 --build-number 6

# flutter build ios --flavor development --release --no-codesign -t lib/main_development.dart  --build-name 1.0.1 --build-number 6
# flutter build ios --flavor production --release --no-codesign -t lib/main_production.dart --build-name 1.0.1 --build-number 6
# flutter build ios --flavor production --release --no-codesign -t lib/main_production.dart --build-name 1.0.1 --build-number 6 --no-tree-shake-icons

version: 1.0.0+1

environment:
  sdk: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # For State-Management
  flutter_bloc: ^8.1.3
  get_it: ^7.6.7
  win32: ^5.5.5

  # For Assets
  flutter_gen: ^5.2.0
  flutter_svg: ^2.0.0
  lottie: ^2.6.0

  # For Localizations
  easy_localization: ^3.0.3

  # For Model
  freezed_annotation: ^2.4.4
  json_serializable: ^6.6.1
  json_annotation: ^4.8.1

  # For Networking
  dio: ^5.1.1
  retrofit: ^4.0.1
  pretty_dio_logger: ^1.3.1

  # For Utilities
  bot_toast: ^4.0.4
  cupertino_icons: ^1.0.2
  flutter_launcher_icons: ^0.13.1
  shared_preferences: ^2.0.18
  connectivity_plus: ^4.0.1
  uuid: ^4.5.1
  flutter_dotenv: ^5.1.0
  emoji_picker_flutter: ^4.2.0
  url_launcher: ^6.2.2
  permission_handler: ^11.0.1

  #tool
  google_mobile_ads: ^5.3.1
  introduction_screen: ^3.1.14
  smooth_page_indicator: ^1.1.0
  chart_sparkline: ^1.1.1
  syncfusion_flutter_charts: ^20.4.48


  # For Images, Files, Videos, button
  font_awesome_flutter: ^10.7.0
  animate_do: ^3.3.4
  image_picker: ^1.0.2
  file_picker: ^8.3.3
  photo_view: ^0.14.0
  photo_manager: ^3.0.0-dev.5
  cached_network_image: ^3.2.3
  video_player: ^2.8.1
  pretty_animated_buttons: ^0.0.2
  shimmer: ^3.0.0
  loading_animation_widget: ^1.3.0
  carousel_slider: ^5.0.0
  #chewie: ^1.8.7
  share_plus: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

  # For Builder
  build_runner: ^2.4.4
  #flutter_gen_runner: ^5.2.0
  built_value_generator: ^8.9.2

  # For Model
  freezed: ^2.5.7

  # For Networking
  flutter_local_notifications: ^17.2.3
  firebase_messaging: ^15.2.5
  retrofit_generator: ^8.1.0
  device_preview: ^1.2.0
  firebase_core: ^3.12.0
  firebase_auth: ^5.5.0
  cloud_firestore: ^5.6.4
  firebase_auth_platform_interface: ^7.6.0

  #for ddap
  qr_code_scanner_plus: ^2.0.10+1
  mobile_scanner: ^5.2.1
  qr_flutter: ^4.1.0
  clipboard: ^0.1.3
  animate_do: ^3.0.2
  web3dart: ^2.7.3
  bip39: ^1.0.6
  ed25519_hd_key: ^2.3.0
  hex: ^0.2.0

flutter_launcher_icons:
  ios: true
  android: true
  remove_alpha_ios: true
  image_path: "assets/icons/music_app_icon.png"

flutter_gen:
  output: lib/generated/
  integrations:
    flutter_svg: true
    lottie: true

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/
    - assets/translations/
    - assets/fonts/
    - assets/icons/
    - assets/htmls/
    - assets/lotties/
    - .env.development
    - .env.production

  fonts:
    - family: NotoSans
      fonts:
        - asset: assets/fonts/NotoSans-Thin.ttf
          weight: 100
        - asset: assets/fonts/NotoSans-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/NotoSans-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/NotoSans-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/NotoSans-Light.ttf
          weight: 300
        - asset: assets/fonts/NotoSans-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/NotoSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/NotoSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/NotoSans-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/NotoSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/NotoSans-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/NotoSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/NotoSans-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/NotoSans-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/NotoSans-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/NotoSans-Black.ttf
          weight: 900
        - asset: assets/fonts/NotoSans-BlackItalic.ttf
          weight: 900
          style: italic
