// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYlt-e4CYmbUO_KWBHkmY_ymaEEhvX-VE',
    appId: '1:740175658307:web:26fa375e8f7509d0ac83f6',
    messagingSenderId: '740175658307',
    projectId: 'send-mail-1f984',
    authDomain: 'send-mail-1f984.firebaseapp.com',
    storageBucket: 'send-mail-1f984.firebasestorage.app',
    measurementId: 'G-WMG0MSQC5W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCXesCPaUL6672J0NPeuKlUYHWSxM0RQM',
    appId: '1:740175658307:android:527cc9d8fe08434aac83f6',
    messagingSenderId: '740175658307',
    projectId: 'send-mail-1f984',
    storageBucket: 'send-mail-1f984.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFhu9aPA8B6pKOznasXW9s_ZkbkGiqbU0',
    appId: '1:740175658307:ios:613b95c78dc44d01ac83f6',
    messagingSenderId: '740175658307',
    projectId: 'send-mail-1f984',
    storageBucket: 'send-mail-1f984.firebasestorage.app',
    iosBundleId: 'com.example.cryptoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFhu9aPA8B6pKOznasXW9s_ZkbkGiqbU0',
    appId: '1:740175658307:ios:613b95c78dc44d01ac83f6',
    messagingSenderId: '740175658307',
    projectId: 'send-mail-1f984',
    storageBucket: 'send-mail-1f984.firebasestorage.app',
    iosBundleId: 'com.example.cryptoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBYlt-e4CYmbUO_KWBHkmY_ymaEEhvX-VE',
    appId: '1:740175658307:web:1ed62888afd3710eac83f6',
    messagingSenderId: '740175658307',
    projectId: 'send-mail-1f984',
    authDomain: 'send-mail-1f984.firebaseapp.com',
    storageBucket: 'send-mail-1f984.firebasestorage.app',
    measurementId: 'G-BJR5QYM9W8',
  );
}
